#cloud-config
# PASSWORD is: ubuntu (I will change it anyway)
# See the autoinstall documentation at:
# https://canonical-subiquity.readthedocs-hosted.com/en/latest/reference/autoinstall-reference.html
autoinstall:
  apt:
    disable_components: []
    fallback: offline-install
    geoip: true
    mirror-selection:
      primary:
      - country-mirror
      - arches: &id001
        - amd64
        - i386
        uri: http://archive.ubuntu.com/ubuntu/
      - arches: &id002
        - s390x
        - arm64
        - armhf
        - powerpc
        - ppc64el
        - riscv64
        uri: http://ports.ubuntu.com/ubuntu-ports
    preserve_sources_list: false
    security:
    - arches: *id001
      uri: http://security.ubuntu.com/ubuntu/
    - arches: *id002
      uri: http://ports.ubuntu.com/ubuntu-ports
  codecs:
    install: true
  drivers:
    install: true
  identity:
    hostname: jrVM
    password: "$6$exDY1mhS4KUYCE/2$zmn9ToZwTKLhCw.b4/b.ZRTIZM30JZ4QrOQ2aOXJ8yk96xpcCof0kxKwuX1kqLG/ygbJ1f8wxED22bTL4F46P0"
    realname: jr
    username: jr
  kernel:
    package: linux-generic-hwe-24.04
  keyboard:
    layout: us
    toggle: null
    variant: ''
  locale: en_US.UTF-8
  network:
    ethernets:
      ens33:
        dhcp4: true
    version: 2
  oem:
    install: auto
  source:
    id: ubuntu-desktop
    search_drivers: true
  ssh:
    allow-pw: true
    authorized-keys: []
    install-server: false
  storage:
    config:
    - ptable: gpt
      path: /dev/sda
      wipe: superblock-recursive
      preserve: false
      name: ''
      grub_device: true
      id: disk-sda
      type: disk
    - device: disk-sda
      size: 1048576
      flag: bios_grub
      number: 1
      preserve: false
      offset: 1048576
      path: /dev/sda1
      id: partition-0
      type: partition
    - device: disk-sda
      size: 322119401472
      wipe: superblock
      number: 2
      preserve: false
      offset: 2097152
      path: /dev/sda2
      id: partition-1
      type: partition
    - fstype: ext4
      volume: partition-1
      preserve: false
      id: format-0
      type: format
    - path: /
      device: format-0
      id: mount-0
      type: mount
  timezone: Europe/Bratislava
  updates: security
  version: 1
