pageinfo = [[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null],
	[0,0,0,0,null]];
pagedata = [ ["./2d-graphics-test.htm","2D Graphics Test","Local video memory (GPU RAM) Tests the video RAM by writing and reading data to and from the RAM on the video card.  Monitor Test (Lines and ...",""],
["./2d_graphics_tests.htm","2D Graphics Test","Lines and Bitmaps This suite contains a number of tests that exercise Qt&#39;s QPainter graphics functions and the video card. The numbers displayed a...",""],
["./3d_graphics_test.htm","3D Graphics Test","Tests the OpenGL&#39;s graphics system.  This test creates and animates a rotating cube with a different color on each side to test the OpenGL fu...",""],
["./acknowledgements.htm","Acknowledgements","The 3D test contains modified example code from published Qt examples.",""],
["./advanced-network-preferences.htm","Advanced Network Preferences","Select network card(s) to test Test mode This drop down selection sets the test mode to be one of the following options: Select Network card IP ad...",""],
["./advanced-network-test.htm","Advanced Network Test","Overview The Advanced Network test allows stability and load testing of up to 12 Network Interfaces (NICs) on a system running BurnInTest.   ...",""],
["./advanced_options.htm","Advanced options","Maintaining multiple test configurations Report Information (Machine ID and Notes) Command Line Parameters Preparing a Customer Test Certificate",""],
["./battery.htm","Battery","This test checks the battery&#39;s level (mWh) and compares this to a threshold value. The threshold value can be specified in absolute, or percentage...",""],
["./battery_preferences.htm","Battery Preferences","BurnInTest can monitor battery levels and report an error if the battery is below a set capacity value in absolute or percentage terms.",""],
["./cd-rom_dvd_preferences.htm","CD-ROM/DVD Preferences","CD/DVD Selection and test method  These fields allow the user to select the CD and DVD drives to be used for the CD/DVD test.  Adding a ...",""],
["./cd_rom_and_dvd_test.htm","Optical Drive Test","Tests the CD-ROM,  DVD and BluRay drives.  This test can be used with many different types of CD / DVD media, including the following ty...",""],
["./command_line_parameters.htm","Command Line Parameters","-C [configname] BurnInTest will load the config file specified.  -D [duration] Sets the test duration to the value specified  in minutes...",""],
["./command_line_version.htm","Command Line Version","The command line version of BurnInTest does not have a Graphical User Interface and as such does not require any graphical libraries to be install...",""],
["./common_error_messages.htm","Common Error Messages","When BurnInTest encounters an error during a test run a short description of the error is displayed in the main window. What follows is an explana...",""],
["./contacting_passmark_software.htm","Contacting PassMark Software","On the Web You can contact PassMark on the web at: https://www.passmark.com/about/contact_us.php  E-Mail For technical support questions, sug...",""],
["./detailed_error_log_history.htm","Detailed Error log history","The detailed error log history can be opened from the ‘View / Error log file’ menu. It contains a record of recent errors and status messages that...",""],
["./disk_preferences.htm","Disk Preferences","Partitioned drives must be mounted before BurnInTest can test them, they also need to be of partition type ext2, ext3, reiserfs, xfs, vfat or ntfs...",""],
["./disk_test.htm","Hard Disk and Floppy Disk Test","This suite contains a number of tests that exercise the mass storage units (Hard disk or otherwise) connected to the computer. By default, the sta...",""],
["./duty_cycles.htm","Test Selection and Duty Cycles","From this window it is possible to configure the automatic stopping of tests, select the tests to be performed and the level of load placed on the...",""],
["./entering_a_licence_key.htm","Entering A Licence Key","Copy your user name and key from the E-mail  Select the entire key, including the -----START_OF_KEY----- and -----END_OF_KEY----- lines &#38;nbsp...",""],
["./error_handling_preferences.htm","Error Handling Preferences","Action on Error When BurnInTest detects an error, three options are available:  Continue The error counter is incremented and testing continu...",""],
["./example_ascii_log_file.htm","Example ASCII Log file","ASCII (Text) log files can be created using the logging option in the Test preferences dialog. The ASCII text log file contains all the informatio...",""],
["./fault_finding.htm","Fault finding","What follows are some hints on how go about finding the cause of particular system instability.  We don’t want to try and explain the steps i...",""],
["./interpreting_the_results.htm","Interpreting the results","Status display In the main window there is a display that shows a summary of all the results of all the tests that are currently running.  Te...",""],
["./logging_preferences.htm","Logging Preferences","Automatic logging Logging to disk is switched on and off with the &#8220;Logging on&#8221; option. When disk logging is on, BurnInTest will log System informa...",""],
["./loopback_plugs.htm","Making Loopback plugs","You can purchase high quality molded loop back plugs from PassMark or, for the serial and parallel versions, you can make your own. A loop back pl...",""],
["./machine_identity.htm","Report Information (Machine ID and Notes)","The fields in this section allow the entry of customer specific information for the system under test. This information is used in the Customer Te...",""],
["./maintaining_multiple_test_configurations.htm","Maintaining Multiple Test Configurations","If you are in the business to testing many different computers then you may benefit from maintaining different test configuration. By saving a par...",""],
["./management-console.htm","Management Console","For BurnInTest users testing large numbers of systems, the BurnInTest Management Console Web server application allows system information, test st...",""],
["./management.htm","Management Console Preferences","Manage BurnInTest with the Console Manager When this option is selected, BurnInTest will send system information, test status and test result info...",""],
["./maths_preferences.htm","CPU Math Preferences","Using the check boxes it is possible to select which maths tests will be performed and which ones will be skipped. See CPU maths test for more det...",""],
["./maths_tests.htm","CPU Maths Test","The CPU test exercises and verifies a wide range of CPU instructions, at user specified loads. The user selectable sub-categories of the CPU test ...",""],
["./memory_preferences.htm","Memory Preferences","One of the test patterns can be selected for the test or the default option Cyclic can be used, which will cycle through each test pattern.",""],
["./memory_test.htm","Memory (RAM) test","Tests the Memory in the computer.  The Memory test, tests the reliability of the RAM installed in the computer.  Some of the available R...",""],
["./menu_options.htm","Menu Options","File Load Test Configuration A test configuration that has been previously saved to disk can be loaded using this menu option. The loaded configur...",""],
["./network_preferences.htm","Network Preferences","Standard Network Test / Advanced Network Test Use these radio buttons to switch between using the standard and advanced network tests.  Advan...",""],
["./network_test.htm","Network Test","The Network test tests your networking hardware and software. This is done by sending special ICMP_ECHO message using the Internet Control Message...",""],
["./other_useful_information.htm","Other Useful Information","Contacting PassMark Software System Requirements Example ASCII Log file Precautions for thorough and careful testing Fault finding Common Error Me...",""],
["./overview.htm","Introduction and Overview","BurnInTest is a software tool that allows all the major sub-systems of a computer to be simultaneously tested for reliability and stability. Anyon...",""],
["./parallel_port_loop_back_plug.htm","Parallel port loop back plug","The parallel port on IBM compatible PCs have always used a DB-25 connector. However, over time several changes have taken place to the electrical ...",""],
["./parallel_port_preferences.htm","Parallel Port Preferences","Parallel port The communications port that will be used by the parallel port test, eg /dev/lp0, /dev/lp1 or /dev/lp2 (only ports currently install...",""],
["./parallel_test.htm","Parallel Port Test","Tests the parallel communications port connected to the PC. The parallel port to be tested can be selected from the Test Preferences window (see s...",""],
["./pcie_slots.htm","PCIe Preferences","Automatically select all PCIe slots with PassMark loopback cards",""],
["./pcie_slot_and_psu_test.htm","PCIe slot and PSU test","When a PCIe test is started, BurnInTest will send a packet of data (using an incrementing byte pattern) to the PCIe test card, which will loop thi...",""],
["./plugin.htm","Plugin","If you have specialized hardware that BurnInTest does not test, you can write your own test and integrate it with BurnInTest.",""],
["./plugin_preferences.htm","Plugin Preferences","You can specify up to 5 external plugin applications.",""],
["./post-test-preferences.htm","Post-Test Preferences","Action: Testing PASSED / Action: Testing FAILED There are different actions that may be taken based on whether a test Passes or Fails, and whether...",""],
["./pre-test_preferences.htm","Pre-test Preferences","You may specify the default behaviour of BurnInTest before it begins any test cycle.",""],
["./precautions_for_thorough_and_careful_testing.htm","Precautions for thorough and careful testing","For a hardware test to be useful several precautions need to be taken. Failure to take into account these factors may result in tests being mislea...",""],
["./preparing_a_customer_test_cert.htm","Preparing a Customer Test Certificate","A Test Certificate is a report targeted at your customer. It includes your company details, Technician information, System summary, Result summary...",""],
["./purchase.htm","How to Purchase BurnInTest","See the PassMark website for current pricing: https://www.passmark.com/sales/",""],
["./quick_start.htm","Quick Start Guide","Here’s a summary of the steps to go through to start testing;",""],
["./scripting.htm","Scripting","BurnInTest includes a simple scripting language that allows tests to be executed in a sequence. ",""],
["./serial_port_loopback_plug.htm","Serial port loopback plug","The serial port on IBM compatible PCs conform to the RS232 electrical standard and use a male DB-9 connector. (older PCs may use a DB-25 in which ...",""],
["./serial_port_preferences.htm","Serial Port Preferences","Adding a serial port To select a serial port for testing, enter the linux serial device name (eg ttyS, TTXRUSB etc), enter the COM port number (0-...",""],
["./serial_test.htm","Serial Port Test","Tests the serial communications ports connected to the PC. Up to 64 serial ports may be tested simultaneously. The serial ports and test speed can...",""],
["./sound_preferences.htm","Sound Preferences","Device Name Sound device name used for testing. Default is \"plughw\" but can also be set to \"default\" (or other sound alias for...",""],
["./sound_test.htm","Sound Test","Sound loopback testing measures the distortion between audio input and audio output. It involves connecting the audio out and line in plugs of you...",""],
["./system_requirements.htm","System Requirements","For the list of supported Linux distributions please refer to this page: https://www.passmark.com/products/burnintest/bitlinux_download.php",""],
["./temperature-preferences.htm","Temperature Preferences","It is possible to monitor, graph and log the temperature of some hardware components while running BurnInTest tests. Temperature values are displa...",""],
["./temperature.htm","Temperature","If the temperature test is selected then an error will be logged if one of the selected temperature sensors exceeds the threshold value that has b...",""],
["./test_descriptions.htm","Test Descriptions","Several tests are built into the software. Each of these tests contains one or more sub-tests designed to exercise different aspects of your compu...",""],
["./test_preferences.htm","Test Preferences","Disk Preferences CPU Math Preferences Memory Preferences Network Preferences CD-ROM/DVD Preferences Parallel Port Preferences Serial Port Preferen...",""],
["./test_window_display.htm","Test Window display","Each test type has its own display window. The contents of the windows are described in the various tests. An example of some of these test window...",""],
["./usb_loopback_plugs.htm","USB Loopback Plugs","USB 3.0 loopback and benchmarking plug USB 3.0 Loopback plugs are one of the fastest methods to diagnose, troubleshoot and load test your PC&#39;s USB...",""],
["./usb_test.htm","USB Test","Tests the USB (Universal Serial Bus) communications ports connected to the PC. The number of USB devices to test can be set in the USB test prefer...",""],
["./usb_test_preferences.htm","USB Test Preferences","Automatically select all USB ports with loopback plugs",""],
["./whats_new.htm","What&#39;s New","Please see our version history online at: https://www.passmark.com/products/burnintest/bitlinux_history.php",""]];
