[ids]
*

[main]
leftalt = layer(alt)

leftshift+rightshift = capslock

shift = oneshot(shift)
meta = oneshot(meta)
control = oneshot(control)

leftalt = oneshot(alt)
rightalt = oneshot(altgr)

capslock = overload(meta, esc)

[alt]
minus = prog1
equal = prog2
semicolon = prog3

