# TODO write CI tests for mac

on:
  push:
    branches: [ "devel", "testing", "stable", "LTS" ]
    paths:
    - 'CommonInitScripts/**.sh*'
    - 'MacOS/**.sh'
    - '.github/workflows/mac.yml'
  pull_request:
    branches: [ "devel", "testing", "stable", "LTS" ]


jobs:
  run-script:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make script executable
        run: chmod +x ./MacOS/packages_install.sh

      - name: Run script
        run: ./MacOS/packages_install.sh
