# TODO write CI tests for mac

on:
  push:
    branches: [ "devel", "testing", "stable", "LTS" ]
    paths:
    - 'CommonInitScripts/**.sh*'
    - 'MacOS/**.sh'
    - '.github/workflows/mac.yml'
  pull_request:
    branches: [ "devel", "testing", "stable", "LTS" ]
