name: Windows

on:
  push:
    branches: [ "devel", "testing", "stable", "LTS" ]
    paths:
    - '*.ps1'
    - 'CommonInitScripts/**.ps1'
    - 'Windows_10/**.ps1'
    - '.github/workflows/windows.yml'
  pull_request:
    branches: [ "devel", "testing", "stable", "LTS" ]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022] # TODO add a newer runner when avaliable

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
      - name: "Install `winget`"
        shell: powershell
        run: choco install winget
      - name: "Run `packages_install.ps1` separatelly (so that it does not pollute logs)"
        shell: powershell
        run: .\Windows_10\packages_install.ps1
      - name: "Run `run_all.ps1`"
        shell: powershell
        run: .\Windows_10\run_all.ps1

# TODO add idempotency test
