name: Windows-latest - initPC script

on:
  push:
    branches: [ "devel", "testing", "stable", "minimal" ]
    paths:
    - 'CommonInitScripts/*.ps1'
    - '.github/workflows/windows.yml'
    - 'Windows_10/*.ps1'
  pull_request:
    branches: [ "devel", "testing", "stable", "minimal" ]
    paths:
    - 'CommonInitScripts/*.ps1'
    - '.github/workflows/windows.yml'
    - 'Windows_10/*.ps1'

jobs:
  build:
    name: Run initPC on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, windows-2019]

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
      - name: "Install `winget`"
        shell: powershell
        run: choco install winget
      - name: "Run `packages_install.ps1` separatelly (so that it does not pollute logs)"
        shell: powershell
        run: .\Windows_10\packages_install.ps1
      - name: "Run `run_all.ps1`"
        shell: powershell
        run: .\Windows_10\run_all.ps1
