name: Windows

on:
  push:
    branches: [ "devel", "testing", "stable", "LTS" ]
    paths:
    - '*.ps1'
    - 'CommonInitScripts/**.ps1'
    - 'Windows_10/**.ps1'
    - '.github/workflows/windows.yml'
  pull_request:
    branches: [ "devel", "testing", "stable", "LTS" ]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["windows-2022", "windows-latest"] # TODO add a newer runner when available
        # TODO make this a single runner when windows-latest is the same as windows-2022

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
      - name: "Install `winget`"
        shell: pwsh
        run: choco install winget.powershell winget winget-cli
      - name: "Test `winget` installation"
        shell: pwsh
        run: winget
      - name: "Run `packages_install.ps1` separately (so that it does not pollute logs)"
        shell: pwsh
        run: .\Windows_10\packages_install.ps1
      - name: "Run `run_all.ps1`"
        shell: pwsh
        run: .\Windows_10\run_all.ps1

# TODO add idempotence test
