name: Windows

on:
  push:
    branches: [ "devel", "testing", "stable", "LTS" ]
    paths:
    - '*.ps1'
    - 'CommonInitScripts/**.ps1'
    - 'Windows_1X/**.ps1'
    - '.github/workflows/windows.yml'
  pull_request:
    branches: [ "devel", "testing", "stable", "LTS" ]

jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    if: |
      !endsWith(github.event.head_commit.message, 'Add a TODO') &&
      !endsWith(github.event.head_commit.message, 'Add TODOs') &&
      !endsWith(github.event.head_commit.message, 'Remove a completed TODO')

      # TODO remove the TODO once this have been tested & add it to the remaining CI tests
    strategy:
      matrix:
        os: ["windows-2022", "windows-latest"] # TODO add a newer runner when available
        # TODO make this a single runner when windows-latest is the same as windows-2022

    steps:
      - name: "checkout repo"
        uses: actions/checkout@v4
      - name: Install winget
        uses: Cyberboss/install-winget@v1
      - name: "Test `winget` installation"
        shell: pwsh
        run: winget
      - name: "Run `packages_install.ps1` separately (so that it does not pollute logs)"
        shell: pwsh
        run: .\Windows_1X\packages_install.ps1
      - name: "Run `run_all.ps1`"
        shell: pwsh
        run: .\Windows_1X\run_all.ps1
      - name: Install optional packages
        shell: pwsh
        run: .\Windows_1X\optional_packages_install.ps1

# TODO add idempotence test
